micronaut:
  application:
    name: pixKeyManagerRest

grpc:
  client:
    plaintext: true
    max-rety-attempts: 10
  channels:
    pixKeyManager:
      address: ${GRPC_URL:`localhost:50051`}
      plaintext: true
      max-retry-attempts: 5